#http
http.host=localhost
http.port=8087

#openrouter
ai.host=openrouter.ai
ai.port=443
ai.key=Bearer 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
model=arcee-ai/trinity-mini:free