#http
http.host=0.0.0.0
http.port=8087

#openrouter
ai.host=openrouter.ai
ai.port=443
ai.key=Bearer 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
model=arcee-ai/trinity-mini:free