#openroute serrvice properties
host.ors=api.openrouteservice.org
port.ors=443

http.host=0.0.0.0
http.port=8081


apiKey=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImZlMjlmZWE1YTEwMjRiOGZhNWUzNzE5ZmY0YTJhNTUwIiwiaCI6Im11cm11cjY0In0=