#properties for prc layer

http.host=0.0.0.0
http.port=8085

common.port = 443

#geopify
host.geopify=sys-geopify-m4-api-bv6fzh.5sc6y6-3.usa-e2.cloudhub.io

#openroute
host.ors=sys-openroute-m4-api-bv6fzh.5sc6y6-3.usa-e2.cloudhub.io

#openmeteo
host.om=sys-openmeteo-m4-api-bv6fzh.5sc6y6-3.usa-e2.cloudhub.io

#ai 
host.ai=sys-openrouter-ai-m4-api-bv6fzh.5sc6y6-1.usa-e2.cloudhub.io